---
# tasks file for docker

- name: Create directory for apt keyrings
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  become: yes
  ansible.builtin.shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Install Docker and related packages
  become: yes
  ansible.builtin.apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes

- name: Install Docker Compose
  become: yes
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure docker group exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present

- name: Add remote user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Doker SDK for Python (from apt)
  become: yes
  ansible.builtin.apt:
    name: python3-docker
    state: present


      # - name: Install docker-compose Python library (with pip)
      #  become: yes
      # ansible.builtin.pip:
      # name: docker-compose
      # state: present
      # extra_args: --break-system-packages
